# Hub:  https://hub.docker.com/_/php
# Tags: https://github.com/docker-library/docs/blob/master/php/README.md#supported-tags-and-respective-dockerfile-links
FROM php:8.4-fpm-alpine

COPY --chown=www-data:www-data . /var/www/html

# USER www-data
# ...
# USER root
