services:
  myproject-service:
    image: myproject_dev
    build:
      context: ./..
      dockerfile: ./docker/Dockerfile
    ports:
      - 80:<http_port>
      - 443:<https_port>
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password=wild
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/aspnetapp.pfx
    volumes:
      # Source code
      - type: bind
        source: ./..
        target: /source

      # HTTPS for development
      - type: bind 
        source: ./../.steven/https
        target: /root/.aspnet/https

      # Git identity
      # TODO: Not every git tool I use is present in the container. This should maybe be a seperate file.
      - type: bind 
        source: ${HOME}/.gitconfig
        target: /root/.gitconfig
